//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class qds117733100_dbEntities : DbContext
    {
        public qds117733100_dbEntities()
            : base("name=qds117733100_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<wx_settings> wx_settings { get; set; }
        public DbSet<wx_userinfo> wx_userinfo { get; set; }
        public DbSet<wx_menu_type> wx_menu_type { get; set; }
        public DbSet<wx_menu> wx_menu { get; set; }
        public DbSet<vyw_wx_menu_type> vyw_wx_menu_type { get; set; }
        public DbSet<wx_log> wx_log { get; set; }
    }
}
